dependencies:
- python=3.10.12
- pip=22.3.1
- pip:
  - albumentations==1.3.0
  - azure-ai-ml==1.8.0
  - matplotlib==3.7.1
  - numpy==1.23.5
  - opencv_python_headless==4.7.0.72
  - pandas==1.5.3
  - Pillow==10.0.0
  - pillow_heif==0.10.0
  - python-dotenv==1.0.0
  - torch==2.0.0
  - torchvision==0.15.0
  - tqdm==4.65.0